#!/bin/bash
#takes in a PATH variable and prepends another folder to it

trap 'rm ~/temp -f' EXIT SIGTERM 
script=$(basename $0)
if [ $# -ne 2 ];then
   echo "$script : format is $script <arg> <arg2>"
   exit 1 
fi 

#check if <arg2> is in <arg1>, should both be strings
cat ~/bin/partials/SHBANG >> ~/temp 
echo "echo \$$1 | grep ^${2}$ > /dev/null" >> ~/temp 
echo 'chk1=$?'   >> ~/temp
echo "echo \$$1 | grep ^${2}: > /dev/null" >> ~/temp
echo 'chk2=$?'  >> ~/temp
echo "echo \$$1 | grep :${2}$ > /dev/null" >> ~/temp
echo 'chk3=$?'  >> ~/temp
echo "echo \$$1 | grep :${2}: > /dev/null" >> ~/temp
echo 'chk4=$?'  >> ~/temp

. ~/temp    #doing this instead of eval
### echo "This is temp:" 
### cat ~/temp 

chk=$((chk1 + chk2 + chk3 + chk4)) 

if [ ! $chk -lt 4 ];then
#not found then prepend to arg1 with : separater 
   echo $2 could not be found in $1 , so we will prepend!
   expand=$(eval "echo \$$1") 
   eval 'export $1="$2:$expand"'
   ### echo "Here is PATH: $PATH"
else  
#found then say so and quit
   echo $2 was found in $1 already
fi

echo "This does not export to current bash shell :("  debug ###

rm ~/temp -f 
