#!/bin/bash
#takes in a PATH variable and prepends another folder to it

script=$(basename $0)

#clean up
trap 'rm ~/temp -f' EXIT SIGTERM 1 2 3 19 20 

#params check
if [ $# -ne 2 ];then
   echo "$script : format is '$script PATH <arg2>'	"
   exit 1 
fi 

#check if <arg2> is in <arg1>, should both be strings
cat ~/bin/partials/SHBANG >> ~/temp 
echo "echo \$$1 | grep ^${2}$ > /dev/null" >> ~/temp 
echo 'chk1=$?'   >> ~/temp
echo "echo \$$1 | grep ^${2}: > /dev/null" >> ~/temp
echo 'chk2=$?'  >> ~/temp
echo "echo \$$1 | grep :${2}$ > /dev/null" >> ~/temp
echo 'chk3=$?'  >> ~/temp
echo "echo \$$1 | grep :${2}: > /dev/null" >> ~/temp
echo 'chk4=$?'  >> ~/temp

#run temp script, sets variables
. ~/temp    #doing this instead of eval

#combine tests into one
chk=$((chk1 + chk2 + chk3 + chk4)) 

# chk = 4 means it already exists in the PATH.  
if [ ! $chk -lt 4 ];then
   #not found, prepend to arg1 with : separater 
   echo $2 could not be found in $1 , so we will prepend!
   expand=$(eval "echo \$$1") 
   eval 'export $1="$2:$expand"'
   sleep 1
   echo
   echo "Here is PATH: $PATH"
else  
   #found then say so and just quit
   echo $2 was found in $1 already
fi

#test for export outside of current shell
