#!/bin/bash
#provides the directory name of a given absolute path
### debugging set -o xtrace

script=$( basename "$0") 
if [ $# -eq 0 -o $# -ge 2 ]; then
   echo "Usage: $script <argument>...(single arg)"  1>&2
   exit 1
fi

IFS='/'
set $@  

dirlist=($@) 
n=$# 
i=0 
while ((i<$n-1)); do  
   echo -n ${dirlist[$i]}
   if [ $i -ne $(($n-2)) ]; then
      echo -n /
   fi
   ((i+=1))
done

if [ $# -gt 1 ]; then
    echo -n /
fi
echo O
