#!/bin/bash
#eachspec runs specs individually

script=$(basename $0)
if [ $# -gt 1 ];then
   echo "$script : format is: $script [<subfolder>] "
   exit 1 
fi 

for file in $(find spec/$1 -name '*\_spec.rb') 
do 	
	echo $1 specs
	bundle exec rspec $file --format doc
	echo "------------------------------------------------"
done
