#!/bin/bash
#takes a file with bash functions and exports them into the environment
script=$(basename $0)
if [ $# -eq 0 ];then
   echo "$script : format is $script <file"
   exit 1 
fi 

function FUNPATH () {
   . $1

   

}


