#!/bin/bash
#tests select control flow

script=$(basename $0)


fruit=(orange papaya apple orange grape pineapple)
trap "echo $script interrupted; exit 1" 1 2 3 19 20	

PS3="Please choose a fruit that you like  " 
select fruit in ${fruit[*]} 
do
	if [ fruit ]; then  
	  echo "Here is your $fruit"
	fi 
	break
done
