#!/bin/bash
#splits a string into an array of strings based on field separater 

#param check
script=$(basename $0)
if [ $# -eq 0 ];then
    echo "$script : format is $script <string> <opt-delim-char>"
    exit 1
fi 

#set field separator
if [ $# -eq 2 ];then
  IFS=$2
else
  IFS=' '   
fi

#separate strings and echo one at a time
list=($1)
for word in ${list[*]}
do
   echo "$word"
done


